scripts/build_prezi2_tests.py, source/api/presentation/2.0/example/fixtures/20/manifest.json, source/api/presentation/2.0/example/fixtures/25/manifest.json
So I can validate with updated validator
=> fix fixtures 20 (multiple seqs) and 25 (service w/o @id)

source/event/2015/washington.md
Proposes this:
| Time           | Session | Presenters |
| -------------- | ------- | ---------- |
| 10:00 - 10:15  | Assemble |  |
| 10:15 - 10:30  | Welcome | Alan Newman |
| 10:30 - 11:00  | Introduction to IIIF | Tom Cramer |
| 11:00 - 11:30  | Solutions Showcase | Stuart Snydman |
| 11:30 - 12:00  | Audience Spotlight and Discussion | Simeon Warner |
| 12:00 - 13:30  | Lunch (not provided)| |
| 13:30 - 15:00  | Demonstrations Showcase | Ben Albritton |
| 15:00 - 15:30  | Coffee |
| 15:30 - 15:50  | Introducing the [Image API][image-api] | Jon Stroop |
| 15:15 - 16:20  | Introducing the [Presentation API][prezi-api] | Robert Sanderson |
| 16:20 - 16:45  | Getting Started | Mike Appleby |
| 16:45 - 17:00  | Next Steps & Close | Tom Cramer |
=> Initial proposal

scripts/build_prezi2_tests.py, source/api/presentation/2.0/example/fixtures/20/manifest.json, source/api/presentation/2.0/example/fixtures/25/manifest.json, source/api/presentation/2.0/example/fixtures/40/manifest.json, source/api/presentation/2.0/example/fixtures/collection.json, source/api/presentation/2.0/example/fixtures/sequence/20/s1.json
Added fixture 40, with multiple labels in metadata. Used as validation test for the validator.
=> Fixing multi-labels for Adam: fixture object

source/api/presentation/2/ontology.xml, source/event/2015/washington.md
... for ruby rdf to generate stubs from (amongst other reasons)
Unblocks sul-dlss/rdf-iiif#1 (@ndushay)
=> Add prezi ontology document

source/event/2015/washington.md
=> Add presenters, fix typo

source/_data/institutions.yml
=> Add Digirati to institutions list, and supply URI for Wellcome Library

source/api/image/2/level2.json
=> closes #471

source/api/presentation/2/annotation_frame.json
=> Fix annotation frame

source/index.html
=> Announce ghent

source/event/2015/ghent.md
There is no Eventbrite mini-event for this. I'm not sure if there needs to be or if it's part of the Unconference.
=> Add Universal Viewer event to Ghent for Friday

source/api/presentation/2.1/index.md
I shouldn't be listed in the Acknowledgements anymore
=> Remove Simeon from Acknowledgements as he is an editor

source/api/auth/0.9/index.md, source/api/image/2.1/index.md, source/css/spec-doc2.scss
* Add @context to auth and all examples
* Update image 2.1 to use auth
* Update description of status codes for auth errors
* Add window closing to 2.1.2
=> Auth context

source/api/image/1.0/index.html, source/api/image/1.1/index.html, source/api/metadata/1.0/index.html, source/community.html, source/technical-details.html
=> Quick updates

source/_data/institutions.yml
We are actively using IIIF and part of the bi-weekly calls, we'd like to be listed. We helped the Qatar National Library implement IIIF for their digital library http://www.qdl.qa/en.
=> Add Cogapp and Qatar National Library to the institutions.yml file

source/api/image/2.1/index.md
I guess I should actually make the PR... see #544 for discussion
=> Warning to explain the sizes issue, fixes #544

source/_includes/copyright.md, source/api/annex/notes/disclaimer.md, source/api/annex/notes/index.html, source/api/annex/openannotation/index.md, source/api/annex/rest/index.md, source/api/annex/services/index.md, source/api/auth/0.9/index.md, source/api/image/2.0/index.md, source/api/image/2.1/index.md, source/api/presentation/2.0/index.md, source/api/presentation/2.1/index.md
=> Add Disclaimer

source/event/2015/ghent.md
Update agenda, add security announcement:
http://ghent_update.iiif.io/event/2015/ghent.html
=> Ghent update

source/api/image/2.1/index.md
This sentence was bothering me. Other suggestions welcome.
=> Clean up first sentence

source/event/2015/ghent.md
Final (I hope) schedule with updated people and titles
=> Ghent schedule

source/api/annex/services/index.md, source/api/image/2/context.json, source/api/image/2/info_frame.json, source/api/presentation/2.1/index.md
Fix the issues that were raised on 2015-12-04 by @aeschylus and @VladimirAlexiev
=> Friday issues

source/api/annex/services/index.md, source/api/image/2/context.json, source/api/image/2/info_frame.json, source/api/presentation/2.1/index.md
Reverts IIIF/iiif.io#628 as it wasn't reviewed be @iiif/editors
=> Revert "Friday issues"

source/_data/institutions.yml
DIAMM will be publishing our image collection using IIIF.
=> Update: Add DIAMM to organizations

source/_data/institutions.yml
See http://api.wdl.org/#iiif for details, http://wdl.org/about for more background about the project
=> Add the World Digital Library to the list

source/api/presentation/2.1/index.md
=> Prezi issues

source/api/annex/openannotation/context.json, source/api/annex/services/physdim/1/context.json, source/api/image/1/context.json, source/api/image/2/context.json, source/api/image/2/info_frame.json, source/api/image/2/level0.json, source/api/image/2/level1.json, source/api/image/2/level2.json, source/api/presentation/1/context.json, source/api/presentation/2/annotationList_frame.json, source/api/presentation/2/annotation_frame.json, source/api/presentation/2/canvas_frame.json, source/api/presentation/2/collection_frame.json, source/api/presentation/2/context.json, source/api/presentation/2/manifest_frame.json, source/api/presentation/2/range_frame.json, source/api/presentation/2/sequence_frame.json
=> no more variables in contexts

source/_includes/beta.md, source/api/image/2/context.json, source/api/presentation/2.1/index.md, source/api/presentation/2/context.json
Add paging relations to presentation, fix context
=> Add Paging relations to Prezi

source/api/presentation/2.1/index.md
Resolves #648 (if not required in Image API too)
=> clarify rendering to support linking to a viewer

.travis.yml
Trivial change to travis config to get us faster checks...
=> Use travis containers, fixes #658

source/api/presentation/2/context.json
If we merge this PR, then the live, current context will change. 
Confirm agreement that this doesn't need to be delayed until 2.1 is released please.
=> Change to dcterms:rights; closes #636

source/api/presentation/2.1/index.md, source/api/presentation/2/context.json
=> Range layer link

_config.yml, scripts/ontologies/mk-image-ontology.py, scripts/ontologies/mk-ontology.py, scripts/ontologies/rdfObject.py, scripts/ontologies/rdfsObj.py, source/api/image/2.1/index.md, source/api/image/2/ontology.xml, source/api/presentation/2/ontology.xml
Closes #631, Closes #551; Closes #523. Properly re-closes #623.
=> 631 ontology

source/_includes/copyright2015.md, source/api/annex/notes/editors.md
Resolves #615. I will squash commits when we're all :+1:
=> Editor's playbook for review.

source/api/annex/notes/index.html
Should have been part of #653.
=> Add link to editors.html link from notes/ page

source/api/image/2/context.json
I don't believe we have this problem in Prezi. Changed tile as well as size for consistency.
Closes #677 (edit to make this link)
=> Rename size/tile, closes #677

source/api/index.md
=> Add reference to notes, closes #681

scripts/call_calendar_generator.rb
A little :gem: to go with our :snake:.
=> Add script for generating call moderator calendars

source/api/image/2.1/index.md
Closes #683.
Would be here: http://dos_warning.iiif.io/api/image/2.1/
=> Add sizeAboveFull DOS warning. 

source/api/search/0.9/index.md
=> Rewrite autocomplete and close #535 too

source/api/image/2.1/index.md
=> Add implementation note for slash parsing

source/technical-details.html
=> Fixes 'All Specifications' link from /technical-details/

source/api/image/2.1/index.md
=> Add impl consideration about directory traversal

source/index.html
=> Linked NYC event from home page

source/api/presentation/2.1/index.md
Move initial integer recommendations to implementation note. Closes #732 
Link: http://initial_int.iiif.io/api/presentation/2.1/#d-implementation-notes
=> Initial int; closes #732

source/api/presentation/2.1/index.md
http://structural739.iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements
=> Add structural properties table; closes #739

source/api/presentation/2.1/index.md
http://range707.iiif.io/api/presentation/2.1/#range
=> Clarify range's contentLayer, add example ; closes #707

source/api/presentation/2.1/index.md
Link: http://within735.iiif.io/api/presentation/2.1/#within
=> Add page clarification to 3/within ; closes #735

source/api/image/2.1/index.md, source/api/image/2/context.json, source/api/image/2/level2.json
http://image_fixes.iiif.io/api/image/2.1/
=> Fix attribution language, consistency of image information, and context

source/api/auth/0/context.json, source/api/image/2/context.json, source/api/presentation/2/context.json
=> swap dc:conformsTo and doap:implements

source/api/image/2.1/index.md
=> Fix vodoo typo

source/_data/institutions.yml
http://add_wp_c2rmf.iiif.io/community/
=> Add C2RMF, wikipedia

source/event/2015/ghent-restaurants.md
Now everyone rebase against this...
=> Fix gado gado link

source/event/2016/newyork/index.md
=> Add Rashmi and Merete

source/_includes/spec-head.html, source/event/2015/ghent-restaurants.md, source/js/anchor.js
I don't really know if I like this, but here it is, for @zimeon
=> update hash fragment when we scroll

source/api/image/2.1/index.md, source/api/presentation/2.1/index.md
Add carefully crafted language selection algorithm to Prezi 2.1
Closes #777
=> Add language algorithm to prezi

source/event/2016/newyork/index.md
=> Schedule tweaks

source/api/index.md, source/api/search/0.9/index.md
=> Make q optional in search, confirm required in autocomplete

source/api/image/2.1/index.md, source/api/presentation/2.1/index.md, source/api/search/0.9/index.md
=> Fix typos from Rob Lancefield

source/api/presentation/2.1/change-log.md
Reviewable at: http://prezi_changelog.iiif.io/api/presentation/2.1/change-log/
=> Changelog for Prezi

source/_data/institutions.yml
=> Add National Library of Scotland

source/css/main.scss, source/event/2016/newyork/index.md
Had a call with NYAM today, and we need to have coffee breaks at set times, and to allow 90 minutes for lunch unless we're paying for everything (which we're not).
This PR updates the schedule given these considerations
=> Update schedule to allow more time for breaks

source/api/annex/notes/editors.md, source/api/annex/openannotation/index.md, source/api/annex/rest/index.md, source/api/annex/services/index.md, source/api/auth/0.9/index.md, source/api/image/2.0/index.md, source/api/image/2.1/index.md, source/api/index.md, source/api/presentation/2.0/index.md, source/api/presentation/2.1/change-log.md, source/api/presentation/2.1/index.md, source/api/search/0.9/index.md, source/api/search/1.0/index.md, source/api/search/1/context.json
This keeps 0.9 - but maybe it should redirect?
=> Search API is now 1.0

_config.yml, source/api/search/0.9/index.md, source/api/search/1.0/index.md
=> Add latest stable version links to search

source/api/presentation/2.1/index.md
Add a note to the "All ... MUST ..." under @type to clarify what all is being described.
http://clarify_type.iiif.io/api/presentation/2.1/#type
Closes #815.
=> Clarify type

config/deploy.rb
=> net/http and conditional Google ping

source/api/presentation/2.1/index.md
=> fix viewingDate to navDate

source/event/2016/newyork/index.md
Move Mark/JHU from today to yesterday when presentation was given. Fix times on Friday.
=> Fix schedule to match reality

_config.yml, source/api/image/2.0/index.md, source/api/image/2.1/index.md, source/api/index.md, source/api/presentation/2.0/index.md, source/api/presentation/2.1/change-log.md, source/api/presentation/2.1/index.md, source/api/search/0.9/index.md, source/api/search/1.0/index.md, source/technical-details.html
Updates that will be required for new releases. Obviously all pending review in the afternoon session today...
=> Prep for 2.1 image/prezi, and 1.0 search release

source/api/presentation/2/context.json
with predicate sc:hasParts, as the range is rdf:List rather than the individual resources.
=> Add members to context

source/api/image/2.0/change-log.md, source/api/image/2.0/compliance.md, source/api/image/2.0/index.md, source/api/presentation/2.0/change-log.md, source/api/presentation/2.0/index.md, source/api/presentation/2.0/zones.md, source/robots.txt
Updates sitemap and robots.txt. We should merge and ping the Google. 👀
=> exclude previous specs from sitemap

source/event/conduct.md
=> Update code of conduct to cover all interactions

source/community/groups/av/index.md, source/community/groups/index.md, source/community/groups/manuscripts/index.md, source/community/groups/museums/index.md, source/community/groups/newspapers/index.md, source/community/index.html
First stab at structure and stubs for community groups in IIIF, fixes #647
=> Stubs for groups

config/deploy.rb
Make cap deployment work again.
Closes #853
=> Make cap >= 3.4

source/community/groups/framework.md
Create a IIIF branch from my own fork, with auto-generated content from google docs.
=> Update/Create framework.md

source/_includes/doctype.html, source/api/annex/notes/editors.md, source/api/image/1.1/change-log.html, source/api/image/1.1/compliance.html, source/api/metadata/1.0/index.html
=> Link to MOU from editoral process

source/api/image/2/context.json
=> image api context dc.rights -> dc.license

source/api/image/2.1/compliance.md
=> remove beta banner from image api compliance 2.1

source/_data/institutions.yml
From list from @tcramer.  Need updates on status of Penn State (@kestlund said they're ready to pay but haven't heard back from Stanford) and Europeana ("it's in my email" said @tcramer)
=> Add new IIIF-C members

source/_data/institutions.yml
=> Add Data Futures Project to list of IIIF-C members

source/_data/institutions.yml
=> Add the Art Institute of Chicago to list of institutions

source/_posts/2016-08-05-community-manager.md, source/index.html
http://copy_announcement.iiif.io/
=> Announcement re: Sheila

source/api/auth/0.9/index.md
These bullets feel like a mix of challenges and requirements. I don't think we need separate lists (though maybe?) because we lay out our goals in the intro, but if this is a list of challenges, we should tighten it up and remove our aspirations.
=> must -> aims to

source/api/auth/0.9/index.md
Trying to tease apart goals and challenges.
=> Revise intro

source/api/auth/0.9/implementation.md, source/api/index.md
=> Bump auth link text to 0.9.3

source/community/groups/manuscripts/index.md
Just a quick update to remove the institutions list and update communications block.
=> Update MSS Community Group

source/_data/institutions.yml
fixes #907 http://add_ncstate.iiif.io/community/consortium/
=> added NCSU to IIIFC members

source/_data/institutions.yml
Closes #909 
See http://add_univtokyo.iiif.io/community/ and http://add_univtokyo.iiif.io/community/consortium/#members
=> added University of Tokyo to IIIFC

source/event/2016/thehague.md, source/event/index.md
Closes #906 
See http://hague_vatican.iiif.io/event/ and http://hague_vatican.iiif.io/event/2016/thehague/
=> Added The Hague and The Vatican to Event

source/_posts/2016-09-12-ncsu-joins-iiifc.md
Announcing NCSU joining consortium plus Nubian Message implementation and other search inside collections.
http://ncsu_news.iiif.io/news/
http://ncsu_news.iiif.io/news/2016/09/12/ncsu-joins-iiifc/
=> ncsu news announcement

source/_posts/2016-09-12-ncsu-joins-iiifc.md, source/_posts/2016-09-16-mirador-upgrade-released.md
News announcement for Mirador 2.1 release
See http://mirador_news.iiif.io/news/2016/09/16/mirador-upgrade-released/
and http://mirador_news.iiif.io/news/
=> mirador2.1 release news

source/api/image/2.1/compliance.md
=> Remove Image API compliance doc draft status, fix redirects

source/api/auth/0.9/index.md
Attempt at fixing #915. Also removed a few unused refs.
=> SHOULD use HTTPS and other security notes

source/community/groups/index.md
Adds the calendar to the community page.
http://calendar.iiif.io/community/groups/
=> try adding calendar to community groups page

source/api/search/0/context.json, source/api/search/1/context.json
=> Fix search contexts

source/_posts/2016-09-30-univ-tokyo-joins-iiifc.md
News announcement for Univ. of Tokyo joining IIIF-C: http://univ_tokyo_announce.iiif.io/news/2016/09/30/univ-tokyo-joins-iiifc/
=> University of Tokyo IIIFC announcement

source/community/consortium/index.md
Updated the staff section of the Consortium page: http://consortium_staff_update.iiif.io/community/consortium/
=> updated staff section

source/api/auth/0/clickthrough.md, source/api/auth/0/external.md, source/api/auth/0/kiosk.md, source/api/auth/0/login.md
=> Redirect from Auth API profile URIs to spec

source/community/index.html
Main change is link to new Google Drive directory, see bottom of the page: http://community_improvements.iiif.io/community/
=> added link to new google drivedirectory, tweaked groups language

source/_data/institutions.yml
Chinese University of Hong Kong has paid and we just now received their MOU - adding them to the official list
=> added Chinese University of Hong Kong to IIIF-C lists

source/api/image/2.1/index.md
=> Fix typo with physdim context/profile URIs in example Complete Response

source/community/groups/museums/index.md
See additional information at http://museums_group_update.iiif.io/community/groups/museums/
Closes #985
=> added more info to museums page

source/_data/institutions.yml
on community and consortium lists 
Closes #970
=> added link to Chinese University of Hong Kong

source/api/presentation/2.1/index.md
=> Canvas deref in Appendix B agrees with text

source/api/image/2.1/index.md
=> Clarify availability of width and height

source/api/presentation/2.1/index.md
=> Use example rights URIs from CC and rightsstatements.org

source/api/image/2.1/index.md
=> clarify max canonical

source/index.html
updated home page news item to point to the IIIF Community Newsletter - see http://homepage_news.iiif.io/
=> updated homepage news to newsletter

source/community/groups/manuscripts/index.md
Standardized Manuscripts group page - see http://manuscripts_group.iiif.io/community/groups/manuscripts/
closes #996 
Standby for review by @blalbrit
=> Manuscripts group

source/event/2017/vatican.md, source/event/index.md
Added initial very basic information about Vatican conference to refer people to for upcoming save the date announcement: http://vatican_info.iiif.io/event/2017/vatican/
Additional info to be added as planning unfolds - many details are still being confirmed...
=> initial info about the vatican event

scripts/call_calendar_generator.rb
:arrow_up: That for @srabun. Names need adjustment.
=> Divides call moderators and alternates call topics between community and tech

source/_posts/2016-12-29-kyoto-univ-joins-iiifc.md
See http://kyoto_univ_announcement.iiif.io/news/2016/12/29/kyoto-univ-joins-iiifc/
=> news announcement for kyoto university library network

source/event/2017/vatican.md
updated schedule to push Outreach plenary to Tuesday June 6
added Exec meeting on Monday June 5
http://vatican_update.iiif.io/event/2017/vatican/
=> updated dates

source/index.html
Updated home page with latest news announcement. Closes #1015
=> Kyoto homepage

source/_includes/copyright2017.md, source/api/annex/notes/design_patterns.md
Creating a PR so we can discuss the specifics of getting this draft out. Fixes #1049
=> Publish design considerations

source/event/2017/edinburgh.md, source/event/index.md
added IIIF Showcase and IIIF Technical unconference events at http://scotland_event.iiif.io/event/2017/edinburgh/
closes #1059
=> added scotland event

source/api/index.md, source/index.html, source/technical-details.html
closes #1067 
See: 
http://trademark.iiif.io/
http://trademark.iiif.io/api
http://trademark.iiif.io/technical-details
=> added TM to requested pages

source/event/2017/vatican.md
updated Vatican event page with links to Eventbrite registration for Showcase and Conference
=> registration info added

source/_data/institutions.yml
=> updated community list

source/community/groups/discovery/charter.md, source/community/groups/discovery/index.md, source/community/groups/index.md
closes #1034 
see http://discovery_group.iiif.io/community/groups/ and http://discovery_group.iiif.io/community/groups/discovery/
@azaroth42
=> added discovery group info

source/index.html
Seems that both @azaroth42 and I find the size of the "TM" on the front page excessive... here is a fix
=> Make TM on front page smaller

source/event/2017/vatican.md, source/index.html
no posting date on home page news item: http://vat-event_adjustments.iiif.io/
adjusted layout of event page: http://vat-event_adjustments.iiif.io/event/2017/vatican/
=> made additional adjustments to vatican event page

source/_data/institutions.yml
I have added Penn State to the IIIF-C list, see: http://iiifc_pennstate.iiif.io/community/consortium/
=> added Penn State to IIIFC

source/_data/institutions.yml
Libaries --> Libraries
http://iiifc_pennstate.iiif.io/community/consortium/
=> fixed typo

source/_posts/2017-02-28-newsletter.md
newsletter up: http://v1i2_newsletter.iiif.io/news/2017/02/28/newsletter/
@azaroth42 @jpstroop @mikeapp @zimeon
=> new newsletter

source/about.html, source/community/consortium/faq.md, source/community/consortium/index.md, source/community/faq/index.md
added the IIIF-C FAQ page at http://iiifc_info.iiif.io/community/consortium/faq/ , linked from http://iiifc_info.iiif.io/community/consortium
This is the first version, I will be adding more content to cover examples and maybe even a map with pins in it to represent location of all IIIF-C members, and other potential ideas for improvement. It's iterative.
@azaroth42 @jpstroop @mikeapp @zimeon
=> Iiifc info

source/community/groups/av/charter.md, source/community/groups/av/index.md
see group page: http://av_charter.iiif.io/community/groups/av/
see charter: http://av_charter.iiif.io/community/groups/av/charter/
=> added charter and updated group page

source/api/presentation/2.1/index.md
=> add thumb example as #1098

source/api/annex/index.html, source/api/annex/notes/design_patterns.md, source/api/annex/notes/index.html
Changes to fix #1100 #1041 #1036 that were the remaining changes to make after final review on the 2017-03-15 community call. Also adds a changelog entry for today noting this review.
=> Patterns document tweaks after 2017-03-15 community call

source/api/image/2.1/index.md
=> Use rightsstatements.org examples

source/api/image/2.1/index.md
Fixes #1104 error pointed out by @anarcivist
=> Use vocab URI not page URI for rightsstatements.org

source/api/annex/services/index.md, source/api/image/2.1/index.md
=> Fix geojson context URI refs

source/_data/institutions.yml
Closes #1092 
added updates from survey results, see: http://commlist_updates.iiif.io/community/#participating-institutions
=> updates to community list

source/api/presentation/2.1/index.md
=> simplify ranges deprecation warning

source/_data/institutions.yml
added Univ. of Virginia to community list upon request
http://adding_uva.iiif.io/community/
closes #1137
=> adding university of virginia

source/_posts/2017-04-12-vatican-conference.md, source/event/2017/vatican.md, source/index.html
News item: http://vatican_promo.iiif.io/news/2017/04/12/vatican-conference/
All sponsors added to event pages
Homepage news link updated
=> Vatican promo

source/_posts/2017-04-12-vatican-conference.md, source/event/2017/vatican.md
Specifying that all events in the Vatican will be conducted in English.
http://events_english.iiif.io/news/2017/04/12/vatican-conference/
http://events_english.iiif.io/event/2017/vatican/
=> added to event materials that the events will be conducted in English

source/_posts/2017-04-27-openjpeg-improvement.md
news announcement for openjpeg project, see http://openjpeg_news.iiif.io/news/2017/04/27/openjpeg-improvement/
=> news announcement for openjpeg

source/_posts/2017-05-01-letter-to-dams.md
letter to DAMS: http://dams_letter.iiif.io/news/2017/05/01/letter-to-dams/
=> letter to dams

source/api/presentation/2.1/index.md
=> ContextAsText -> ContentAsText

source/_data/institutions.yml
Added Leipzig to the community list: http://leipzig.iiif.io/community/#participating-institutions
=> added Leipzig University to commnunity list

_config.yml, source/api/presentation/2.1/change-log-211.md, source/api/presentation/2.1/index.md
Add changelog for Presentation API, update headers for API documentation, add entry in in-document version history.
=> Prezi changelog 2.1.1

_config.yml, source/api/image/2.1/change-log-211.md, source/api/image/2.1/index.md
As close in style to the prezi one as possible
=> changelog for Image API 2.1.1

source/_posts/2017-05-25-newsletter.md, source/index.html
Newsletter is up: http://newsletter3.iiif.io/news/2017/05/25/newsletter/
Link to newsletter on home page: http://newsletter3.iiif.io/
=> Newsletter3

_config.yml, source/api/annex/services/index.md, source/api/image/2.1/change-log-211.md, source/api/image/2.1/index.md
This is the collection of changes related to the 2.1.1 Image API Milestone
=> WIP - DO NOT MERGE Image 2.1.1

source/api/image/2.1/index.md, source/api/presentation/2.1/index.md
=> Fix 2.1.1 dates to today

source/community/call/index.md, source/community/groups/av/index.md, source/community/groups/discovery/index.md, source/community/groups/manuscripts/index.md, source/community/groups/museums/index.md, source/community/groups/newspapers/index.md, source/community/groups/software/index.md, source/event/2017/toronto.md, source/event/index.md
see: http://update_events.iiif.io/event/
and: http://update_events.iiif.io/event/2017/toronto/
=> updated events page and added page for Toronto

source/community/groups/index.md, source/community/groups/text-granularity/charter.md, source/community/groups/text-granularity/index.md
added text group info to:
http://text_group.iiif.io/community/groups/
http://text_group.iiif.io/community/groups/text-granularity/
http://text_group.iiif.io/community/groups/text-granularity/charter/
=> added text granularity group info

source/_data/image_servers.yml, source/_data/impl_demos.yml
http://apps_demos_update.iiif.io/apps-demos/
Closes #1179
=> Apps demos update

source/_posts/2017-05-01-letter-to-dams.md
See: http://dams_museum.iiif.io/news/2017/05/01/letter-to-dams/
=> added Royal Library of Belgium upon request

source/community/groups/newspapers/index.md
http://newspaper_update.iiif.io/community/groups/newspapers/
closes #1202
=> newspaper group calls are now quarterly

source/_data/institutions.yml
Folger just joined the IIIF-C - I can't deploy the branch bc "no space left on device"...
=> added folger to iiif-c list

source/api/annex/index.html, source/api/annex/notes/index.html, source/model/shared-canvas/1.0/index.html
Hi,
Had to read the presentation and search API's for a presentation and noticed a few typos here and there.
Not sure what is the policy for updating old/current specs. I can update the pull request in case only a subset of the changes are useful - if any at all :-)
Bruno
=> Fix some minor typos

source/event/2017/toronto.md
added registration link, hotel info, etc.: http://toronto_update.iiif.io/event/2017/toronto/
=> updated toronto working meeting info

source/event/2017/london.md, source/event/index.md
Not sure what happened with my branch name. in any case: 
http://v.iiif.io/event/
http://v.iiif.io/event/2017/london/
=> added v&a event

source/_posts/2017-08-21-iiif-in-japan.md
http://japan-news.iiif.io/news/#iiif-in-japan-21-aug-2017
=> news posting about iiif event in japan

source/_data/institutions.yml
http://adding-nga.iiif.io/community/consortium/
NGA is joining IIIF-C
=> added national gallery of art to consortium list

source/_data/institutions.yml
http://smithsonian_iiifc.iiif.io/community/consortium/
=> added Smithsonian to IIIF-C

source/_data/institutions.yml, source/_posts/2017-08-30-newsletter.md
had to replace SLU link per request: http://slu_link.iiif.io/community/consortium/
made a few minor updates to newsletter: http://slu_link.iiif.io/news/2017/08/30/newsletter/
=> updated SLU link and added CIDOC to newsletter

source/event/2017/toronto-showcase.md, source/event/2017/toronto.md
http://toronto-plenaries.iiif.io/event/2017/toronto/#wednesday-october-11-afternoon
http://toronto-plenaries.iiif.io/event/2017/toronto-showcase/
=> added plenaries to toronto schedules

source/_data/institutions.yml
added OCLC to iiif-c list: http://oclc_iiifc.iiif.io/community/consortium/#members
=> OCLC joined iiif-c

source/_includes/links.md, source/api/presentation/3.0/index.md, spec/source/syntax_spec.rb
Proposal. Now that the site has been pared down, centrally manage links in an include? I have constantly having to scroll to the bottom.
=> add links include

source/api/presentation/3.0/index.md
Fixes #1185 formatting issue, I agree otherwise done
=> Issue 1185 typo in type description

source/api/presentation/3.0/index.md
Closes #1064 (only editorial, no normative requirements)
=> 1064 contexts

source/api/presentation/3.0/index.md
=> Add client reqs for default nav structure, improve description

source/_includes/links.md, source/api/presentation/3.0/index.md
Closes #1214 ; add section with recommendations on URI best practices
=> add URI recommendations section

source/api/presentation/3.0/index.md
Closes #1239 ; adds id via # kramdown syntax to each table in prezi3 spec
=> add id attrs to tables

source/api/presentation/3.0/index.md
Closes #1176 ; Clarifies that multiple thumbnails can be of the same type and or format
=> clarify multiple types

source/api/presentation/3.0/index.md
Closes #1065 ; Add language property as technical metadata.
=> 1065 language

source/api/presentation/3.0/index.md
Closes #1321. Use HTTP(S) consistently throughout.  Make more example URIs https.
=> Use "HTTP(S)"

source/api/presentation/3.0/index.md
=> Two http(s) to HTTP(S) fixes

source/api/presentation/3.0/index.md
=> Replace remaining instance of Layer with AnnotationCollection, AnnotationList with AnnotationPage

source/api/presentation/3.0/index.md
Closes #1322 ; make section 3 consistent (and update `annotations` description)
=> 1322 this resource

source/api/presentation/3.0/index.md
Closes #1126.  Adds example and notion of deref, without making normative requirements that are impossible to keep.
=> Add extensive examples for within-ness

source/api/presentation/3.0/index.md
=> fix string labels

source/_includes/links.md, source/api/presentation/3.0/index.md
Closes #1121 ; add ImageService1,2 and SearchService1 to Prezi3
=> 1121 services

.gitignore, source/api/index.md
Adding authentication translation as requested in #1052.
=> Add Japanes Auth translation

README.md
=> Add contribution statement to README

source/api/presentation/3.0/index.md
Closes #1361  (despite what the branch name implies)
=> h/w to MAY to not prejudice against pure audio

source/api/presentation/3.0/index.md
=> Clarify collection descriptions

source/api/presentation/3.0/index.md
=> rename startCanvas->start, clarify fragments

source/api/presentation/3.0/index.md
=> AnnotationCollection|Page to Annotation Collection | Page in text

source/api/presentation/3.0/index.md
=> remove navDate UTC requirement, allow on Range

source/api/presentation/3.0/index.md
=> Edits on section 1 and 2

source/api/presentation/3.0/index.md
=> Remove paging, closes #1343

source/_includes/links.md, source/api/presentation/3.0/index.md
=> fix cardinalities consistency

source/api/presentation/3.0/index.md
Trivial fixes to agree with rest of current spec
=> Fix JSON examples: sequences->items, structure->structures

source/_includes/links.md, source/api/presentation/3.0/index.md
We didn't have a link in the prezi3 spec.
=> Link to media frags spec

source/api/presentation/3.0/index.md
=> reformat allllll the json

source/api/image/3.0/compliance.md, source/api/image/3.0/index.md
=> full -> max

source/api/image/3.0/compliance.md
=> make square req at 1

source/api/image/3.0/compliance.md, source/api/image/3.0/index.md
=> 693 size above full

source/api/image/3.0/index.md
=> 1090 media type

source/api/image/3.0/index.md
=> ImageService3 type

source/api/image/3.0/index.md
=> add level 0 to scope

source/api/image/3.0/index.md
=> Update canonical size to w,h

source/api/image/3.0/index.md, source/api/presentation/3.0/index.md
Fixes #1441 , also add dummy date line for image
=> Fix acknowledgements to members of the IIIF community

source/api/presentation/3.0/index.md
=> canvas on canvas

source/api/image/3.0/implementation.md
=> Reorganize and add size constraints to Image implementation notes

source/api/image/3.0/index.md, source/api/presentation/3.0/index.md
=> Fix examples to https and format JSON in Image API, fix JSON for services in Prezi

source/api/presentation/3.0/index.md
=> unrequire deref of annotation page

source/_includes/links.md, source/api/presentation/3.0/index.md
=> 1459 extension

source/api/presentation/3.0/index.md
=> fix table header

source/api/image/3.0/index.md
=> Tidy Image API language

source/api/image/3.0/index.md, source/api/presentation/3.0/change-log.md, source/api/presentation/3.0/index.md
=> Fix double spaces

source/api/image/3.0/index.md
Closes #1472 -- might want to later adjust full example again to use a real extension but for now have put in an example.org one
=> Fix Image API @context description to allow single or multiple

source/api/image/3.0/index.md
=> Make Image API example 5.5 complete

source/api/presentation/3.0/index.md
Remake anno target change with Tom's better wording.
=> remake anno target change

source/api/presentation/3.0/index.md
=> Add annotations to objectives

source/api/presentation/3.0/index.md
=> includes/transcribing -> supplementary/supplementing

source/api/presentation/3.0/index.md
=> language to SHOULD, simplify examples

source/api/presentation/3.0/index.md
=> forbid javascript: in href

source/api/presentation/3.0/index.md
=> Prezi3 example fix to add missing type -- trivial

source/api/presentation/3.0/index.md
=> Add paged example

source/_includes/links.md, source/api/annex/registry/rights/index.md, source/api/presentation/3.0/index.md
* Create a registry for rights
* Rework rights to be enumerated list
* Add CC and RS.o entries
* Move summary up (#1464)
* Add extraneous pedagogical text to label and summary.
Closes #1479 ; Closes #1464
=> 1479 rights

source/api/annex/notes/design_patterns.md
Closes #1284 ; Closes #1131  ; Closes #590
=> JSON-LD Design Patterns

source/api/image/3.0/index.md
=> Fix floating point description

source/api/presentation/3.0/index.md
=> whitelist http/s, mailto ; explain client requirement not publisher

source/api/annex/notes/design_patterns.md
=> clarify IIIF contexts only for JSON-LD design patterns

source/api/image/3.0/index.md
=> clarify return w,h can be < requested for bang w,h

source/api/presentation/3.0/index.md
=> clarify start of duration canvases and navDate

source/api/presentation/3.0/index.md
=> Move reqs for referenced content in Collection to 5.1

source/_includes/links.md, source/api/presentation/3.0/index.md
Closes #1496 (though we need to remember the pattern for future APIs)
=> ack to AV TSG in Prezi3

source/api/presentation/3.0/index.md
=> Allow navDate on Canvas

source/api/image/3.0/index.md, source/css/spec-doc3.scss
=> Format rule application to Image API 3

source/api/presentation/3.0/index.md
=> Content resources are not a class

source/api/image/3.0/index.md
=> Add example service

source/api/presentation/3.0/index.md
Closes #1544 
Note also adds in http://prezi3.iiif.io/api/presentation/3.0/#structural-properties that items and structure MUST NOT appear on other resources
=> Add structural properties table

source/api/presentation/3.0/index.md
=> compile full example

source/api/presentation/3/classes.json, source/api/presentation/3/context.json
=> split classes from prezi3 context

source/api/presentation/3.0/index.md
in Prezi3 section 5 ; Closes #1556
=> Consistent headings

source/api/image/3.0/index.md, source/api/presentation/3.0/index.md, source/css/main.scss, source/css/spec-doc3.scss
=> Fix names and css

source/api/presentation/3.0/index.md
Fixes #1595 
Range was also incorrect. I tidied up the whitespace in the table markdown too.
=> Sort out tables for #1595 and #1608

source/api/presentation/3.0/change-log.md
One for http://iiif.io/api/presentation/3.0/change-log/#141-remove-sequence-in-favor-of-ranges-items-and-behavior-value-sequence seems particularly helpful re readibility
=> Add 3 serial commas to Prezi3 change log

source/api/discovery/0.1/index.md
Propose to merge to master as it's a silly typo in a 0.x document.
=> Fix target/object typo

source/_includes/links.md, source/api/index.md
Add link to change discovery API to table.
=> link the change discovery API from /api/

source/api/image/3.0/change-log.md
=> Add note about change to canonical form of tile requests

source/api/image/3.0/index.md, source/api/presentation/3.0/index.md
=> Recommend support for HEAD in Image and Presentation 3.0

source/api/image/3.0/index.md
Closes #1587 when combined with PR #1652 (for issue #1606)
=> Note other parameters allowed

source/api/image/3.0/index.md
=> Recommend application/ld+json

source/api/presentation/3.0/index.md
=> ref openanno annex

source/api/presentation/3.0/index.md
=> fix array in manifest eg

source/api/presentation/3.0/change-log.md
=> move 2.1.7 to 2.1.1

source/api/image/3.0/index.md
=> Improve wording in 5.1. Image Information Request

source/api/presentation/3.0/index.md
=> 1615 poster canvas

source/_includes/links.md, source/api/presentation/3.0/index.md
Closes #1620 ; Closes #1618 ; Closes #1608 ; Closes #1595
=> fix various table issues and dependent text

source/api/presentation/3.0/index.md
=> remove comments and extraneous , from json

source/api/image/3.0/compliance.md
=> Fix outdated link in compliance

source/api/presentation/3.0/index.md
small typo: summmary -> summary
=> prezi typo

source/api/image/3.0/index.md, source/api/presentation/3.0/index.md
=> Update to beta

source/api/presentation/3.0/index.md
=> Reapply normative changes for content dimension properties

source/api/presentation/3.0/index.md
This seems to keep GitHub happy
=> Escape footnote asterisks with backslash

source/api/presentation/3.0/index.md
=> Remove Application, Remove Service, add Model

source/api/image/3.0/index.md
=> s/complete/full/ in Size param

source/api/presentation/3.0/index.md
=> Add Canvas.annotations examples

source/_includes/links.md, source/api/presentation/3.0/index.md
=> update tables, name, links

source/api/image/3.0/index.md, source/api/presentation/3.0/index.md
=> Reorder description of conneg and content types in Image and Prezi 3.0

source/api/presentation/3/combined-context.json
=> Change / to # in service URIs

source/api/presentation/3/combined-context.json
=> rename image/presentation to internal name

source/api/presentation/3/combined-context.json
=> update Service, protocol, conformsTo

source/_includes/links.md, source/api/discovery/0.2/index.md, source/api/discovery/0/context.json, source/api/index.md
Minor text updates, plus addition of `describedBy` for the use case of referencing related descriptions.
=> Discovery API 0.2

source/api/discovery/0/context.json
=> Errant comma

source/_includes/links.md, source/api/presentation/3.0/index.md
=> Fix link to profiles registry

source/api/presentation/3.0/index.md
=> Add missing br tags

source/_includes/links.md
=> fix links after adding case at top of section 4

source/api/presentation/3.0/index.md
=> fix 1 character typo

source/api/image/3.0/index.md
Copied from first example in section.
=> add max* to complete example

source/api/image/3.0/index.md
=> add extra* from complete

source/api/annex/notes/design_patterns.md
=> Add worldwide use design pattern

source/api/presentation/3.0/index.md
=> Client should choose logo based on properties

source/api/presentation/3.0/index.md
To use `max` and consistent URI structures
=> Update Image API examples in Prezi

source/_includes/links.md, source/api/image/3.0/index.md
=> [TRC-DNM] 1787 remove logo reqdstmnt from image

source/_includes/links.md, source/api/image/3.0/index.md
=> Revert "[TRC-DNM] 1787 remove logo reqdstmnt from image"

source/_includes/links.md, source/api/image/3.0/index.md
Not a DNM. Re-merges accidentally umerged work to close #1787
=> 1787 remove logo reqdstmnt from image

source/api/presentation/3.0/index.md
Maybe a little more emphasis? I tried putting the bit about image services in a {: .note } box but that looked a bit odd.
addresses #1798
=> [WIP] a remix of 5.7 Content Resources

source/api/image/3.0/index.md
=> Clarify max does not ask for upscaling, ^max does

source/api/presentation/3.0/index.md
Fixes #1730
Also has a couple of line end and other space fixes
=> Use consistent form for normative property descriptions

source/api/image/3/context.json
=> 1821 imageprofile

source/api/presentation/3.0/index.md
=> Explain @ keywords

source/api/presentation/3.0/index.md
=> Fix label examples in 4.2 and 5.1, fix spacing in other examples

source/api/image/3.0/change-log.md
@mikeapp I think there is only one remaining normative change to be written up:
* https://github.com/IIIF/api/issues/1703
[There are about 20 Non-normative changes to consider for inclusion](https://github.com/IIIF/api/issues?utf8=%E2%9C%93&q=is%3Aclosed+is%3Aissue+label%3Aimage+-label%3Awontfix+label%3Anormative+closed%3A%3E2018-09-19+-label%3Anormative)
=> rc2 image changelog

source/api/presentation/3.0/index.md
Make lots of little editorial changes, per #1836
=> 1836 editorial

source/api/image/3.0/index.md
=> example and use case for preferredFormats

source/api/presentation/3.0/index.md
=> Add format property to thumbnail and logo examples

source/api/presentation/3.0/index.md
=> Be consistent that `type` is required with `thumbnail` and `logo`

source/api/presentation/3.0/index.md, source/api/presentation/3/context.json
=> revert to always use label as language map

source/api/image/validator/index.html
Currently only supports level 0 but working on supporting the other levels.
=> Adding support for 3.0 

source/api/image/3/level1.json
#1799 as solution for  #1785 did not include the necessary change to the compliance level document.
=> Add sizeByWh to level1.json

source/api/presentation/3.0/index.md
Adds label to example.
Closes #1858
=> add label to seeAlso example

source/_includes/links.md
=> fix 1.3 -> 1.2 terminology

source/api/presentation/3.0/index.md
Remove reference to removed table of protocol requirements
Closes #1866
=> fix 6.3 para 1

source/_includes/links.md, source/api/extension/text-granularity/context.json, source/api/extension/text-granularity/index.md
https://preview.iiif.io/api/text-granularity/api/extension/text-granularity/
See issue #758
=> Text granularity extension property

source/api/presentation/3.0/index.md
=> Fix SHOULD not --> SHOULD NOT

source/api/image/3.0/index.md
=> Fix extraFormats in complete response, fix MUST in preferredFormats

source/api/presentation/3.0/index.md
Closes #1873
Note that this is a substantive, normative change and requires TRC approval.
Approval request: https://github.com/IIIF/trc/issues/31
Do not merge before TRC approves.
=> Allow shared services pattern

source/api/presentation/3.0/index.md
Closes #1874 per https://github.com/IIIF/trc/issues/32
=> Use http for CC URIs

source/api/presentation/3.0/change-log.md
#1864 for presentation change log, see also #1831
Shamelessly cribbing from @azaroth42's #1907
=> Note context change in prezi3

source/api/image/3.0/change-log.md
Add changelog entry for `@context.  Closes #1864
=> add entry for @context

source/api/annex/services/index.md, source/api/image/3.0/index.md
=> add service example to image, add list of types to annex

source/api/presentation/3.0/change-log.md
Only two missing entries that I could find from RC3.
Assigning to @zimeon for his double-check.
=> add missing prezi changelog entries

source/api/discovery/0.5/index.md
V0.5 - Date and description missing in the change log. I put today's date but it may be a different one I suppose.
=> Missing information in the Change Log

source/api/presentation/3.0/index.md
=> add changelog entry for beta2

source/_includes/links.md
=> update _links table from 57 to 58

source/api/presentation/3.0/change-log.md, source/api/presentation/3.0/index.md
=> add id to start example, fix iif typo, update changelog

source/api/presentation/3.0/change-log.md, source/api/presentation/3.0/index.md
Remove rights from language and update changelog, thanks to Mark Matney.
Closes #1933
=> remove rights from language, update changelog

source/api/presentation/3.0/index.md
=> clarify URI construction to Prezi API

source/_includes/links.md, source/api/discovery/0.5/index.md
Wordsmithy and typo stuff only
=> JS editorial readthrough

source/api/presentation/3.0/index.md
=> fix extra class list

source/api/image/3.0/index.md
This does not feel right, but is consistent with the decision in https://github.com/IIIF/trc/issues/25. Closes #1922.
=> Clarfiy that color may still be grayscale, etc.

source/_includes/links.md, source/api/extension/index.md, source/api/registry/index.md
Fixes https://github.com/IIIF/api/issues/1932
=> Linking up Extensions registry

source/api/index.md
=> Add links to image and presentation 2.1 in table of old versions

source/api/discovery/0.9/index.md
Update Rob's institution, and fix Discovery issues 77,78,79.
=> #77, #78, #79 editorial updates

source/_includes/links.md, source/api/registry/index.md
=> Clarify description of extensions registry, link to activity streams registry

source/_includes/links.md, source/api/discovery/0.9/index.md
=> add reference to registry

source/api/presentation/validator/service/index.html
Relates to: https://github.com/IIIF/presentation-validator/issues/104
=> Adding UX to show validation is happening.

source/api/discovery/0.9/index.md
Add Refresh and other 0.9.1 features discussed over last calls.
=> Refresh and Non IIIF Resource Types

source/api/content-state/0.3/index.md
Fixes https://github.com/IIIF/discovery/issues/88
Is there anything to be gained by not hard-coding this as I have done here?
=> hard-coded Presentation 3 context in Content State 0.x

source/api/content-state/0.3/index.md
=> Fix @regisrob comments; typos in Content State API

.travis.yml
I think this is the only change required. Not sure of sequence but I may try and merge these before renaming the branch.
=> Rename master to main

source/api/discovery/0.9/index.md
Discovery and all approved this (non versioned) change, as requested by Antoine
=> 1 word change for Antoine

_config.yml, source/_includes/links.md, source/api/discovery/1.0/index.md, source/api/index.md
PR to merge when TRC approves 1.0 (assuming it does)
=> discovery 1.0

source/api/discovery/1/context.json, source/api/discovery/1/ontology.xml
Updating from 0/ context per discovery#92
=> Add discovery 1/ context file

source/_includes/links.md
make main green by fixing links
=> fix duplicate links

source/api/content-state/0.9/index.md
fixes #2047
This also corrects the string padding algorithm thanks to @zimeon
=> Update padding description, fix string length, small editorial tweak

source/content-state/0.9/index.md
Merge #2078 first! This will leave just last commit (and hopefully no conflict)
Remove @jpstroop from editor list on Content State 0.9 at his request
=> Remove Jon from editor list on Content State

source/index.md
added Chinese translations of the APIs to the community translations list.
=> Add translations

Gemfile.lock
We are adding a general page feedback form to make it easier for users to let us know of any corrections or comments. This work is done on the jekyll theme so requires an update for all of the websites. 
The only change in this pull request is the version of the theme.
=> Adding website feedback form

source/api/search/2.0/index.md
=> Fix old typo uri->user in table

source/presentation/3.0/index.md
Fixes #2010 
Preview: https://preview.iiif.io/api/2010_http_rights/presentation/3.0/#b-example-manifest-response
=> Change https to http in CC URI

source/content-state/0.9/index.md
=> Remove duplicate TOC on Content State

source/_includes/links.md, source/api/search/2.0/index.md
Closes #2071 
I have left the `[ignored-parameters]` link, as it is to an internal anchor on the page, so I don't think it's suited for links.md
=> Include links.md and update inline links as necessary

Gemfile, Gemfile.lock, _config.yml, source/_includes/links.md, source/content-state/0.1/index.md, source/content-state/0.2/index.md, source/content-state/0.3/index.md, source/content-state/0.9/index.md, source/content-state/1.0/index.md, source/index.md
Pull request to push Content state to level 1.0. This is now up for approval by the TRC.
Small changes that will be required before merging:
=> Content state version 1.0

source/index.md
So that we can start linking to this in #2005 etc
=> Add section and anchor for feedback, to link from specs

Gemfile.lock, source/search/2.0/index.md
Updating theme for the `/api/` page and using the correct variables in the search page.
=> Setting latest search version to v2

source/registry/profiles/index.md
Adding DC Terms to the list of profiles
=> Adding DC Terms to the list of profiles

source/registry/profiles/index.md
Per discussion on Discovery call of 2022-12-14
=> Add linked art, lido, wikidata & darwin core

source/auth/2.0/index.md
Add property grid and definitions to the logout service so that it matches other service descriptions.
Preview: https://preview.iiif.io/api/logout_service_description/auth/2.0/#logout-service
=> Logout service description

Gemfile.lock
=> Theme update for Auth2 entry on API index page

source/presentation/3/context.json
Fixes:
#2297 Remove `"@container": "@set"` from viewingDirection
#2223 Update `dcterms:partOf` to `dcterms:isPartOf`
#2139 Add contentState and contextualizing motivations
=> Presi context file fixes

source/presentation/4.0/model.md
Fix type of WktSelector, fix small typo in TextualBody
=> Fix type of WktSelector
