- source/_data/institutions.yml
Replaced „Codices Electronici Sangallenses“ with „e-codices“ and added
„text & bytes“ to the participating institutions
> Updated "Community" config info

- source/_data/image_clients.yml
Version 4.0 of Diva.js adds IIIF compatibility. This commit updates the Image Viewing Clients section to include Diva.js.
> Add diva.js to the IIIF-compatible image clients

- source/_data/image_clients.yml
Now that Leaflet-IIIF is in production in several places, putting it on the IIIF website. Not sure what happened to this site:
http://showcase.iiif.io/
But leaflet-iiif is there as well
> add Leaflet-IIIF to image viewing clients

- source/api/auth/0.9/index.md
- source/api/image/2.1/index.md
When I added the alert note to the Image API 2.1 I modified the wrong text (cut and pasted and then modified auth ...) :facepunch:
> Reversed alert notes

- source/api/image/2.0/index.md
Tidy change log in Image 2.0 to include the actual release date, and be a little more consistent for other entries
> Fix change log, fixes #640

- source/api/image/2.1/change-log.md
- source/api/image/2.1/index.md
Tidies change log in Image 2.1, strips out content from change log document copied from 2.0 leaving headings for changes that we need to flesh out descriptions of, fixes a couple of minor formatting issues
> Tidy 2.1 change log, canonical example, formatting. Fixes #639, Fixes #641

- source/api/presentation/2.1/index.md
- source/api/search/0.9/index.md
Removes from prezi-21 and search-09, I assume we leave in prezi-20.
> Remove Usage headers in prezi and search specs, fixes #651

- source/api/auth/0/context.json
I minted an auth NS, and included image and prezi NS even though they're not needed directly.
Otherwise the only three keys needed are label, service and profile.
> Add context for auth; closes #637

- source/api/image/2.1/compliance.md
- source/api/image/2.1/index.md
Add maxWidth/maxHeight/maxArea, clarify compliance document regarding support for combinations of parameters, number compliance document sections following form of Image API, give Level 0 its own section. Fixes #620
> Add maxWidth/maxHeight/maxArea, clarify compliance

- source/api/presentation/2/context.json
Closes #638. Visible at http://638_seealso.iiif.io/api/presentation/2/context.json
> page --> seeAlso

- Rakefile
> Remove redundant rm; Use 'jekyll clean'

- source/api/annex/services/index.md
Replaces page.major with site.image_api.latest.major for image API version and fixes an instance with extra explicit `/2/`. Closes #731
> Fix http://iiif.io/api/annex/services/ examples to use site image API version

- source/api/presentation/2.1/index.md
Closes #716.
PR is not likely ready, but now you can see the diff. First draft is here:
http://membership.iiif.io/api/presentation/2.1/
A few questions:
Feedback welcome.
> Add Members

- source/api/image/2.1/compliance.md
- source/api/image/2.1/index.md
- source/api/image/2/level0.json
- source/api/image/2/level1.json
- source/api/image/2/level2.json
Fixes https://github.com/IIIF/iiif.io/issues/720
Question - those profiles are for 2.0 too (because semver) - is that a problem? 
Fixes sizeByForcedWh syntax typo in compliance doc
Question - should this be fixed in the 2.0 compliance doc too?
> Size and profile clarifications

- source/api/auth/0.9/index.md
- source/api/presentation/2.1/index.md
Closes #756 by addressing current drafts of prezi 2.1 and auth 0.9.x
> Rename auth and prezi API docs

- Rakefile
Make the link checker only run every 4 weeks.
> Wider remote link check interval

- source/api/image/2.0/compliance.md
- source/api/image/2.0/index.md
from Image API 2.0. Checked the other specs and couldn't find any more.
> remove double lines

- source/api/presentation/2.1/index.md
Non normative fix to Presentation API rendering property description from __ to _ of an RFC MUST.
Fixes #782.
(Not deploying temporary site for a two character fix)
> Fix __ to _ typo for RFC MUST

- source/api/image/2.1/change-log.md
Have taken what I think is a complete pass at the changelog for Image 2.1 based on @jpstroop's start. Needs attention from other eyes.
> Image changelog for 2.1, fixes #614

- source/event/2016/newyork/index.md
Adds Tina Shah (Art Institute of Chicago) to list of Museums WG facilitators.
> Adding Tina Shah to Museums WG facilitators

- source/event/2016/newyork/index.md
Perhaps we'll want to add a couple of other tweaks but so far I have:
* Moved metadata search to Thursday 3pm
* Shifted MediaChain up to 4pm on Friday
* Changed "IIIF A/V Update" to "IIIF A/V Update & Discussion" since I don't want to give the impression that this is eds speaking for 90mins!
> Conference schedule tweaks

- source/api/presentation/2.1/index.md
http://specific_image.iiif.io/api/presentation/2.1/#image-resources
Add note that just because it SHOULD be an image, doesn't mean that it always will be one, and there are lots of valid situations to test for.
Closes #816
> Clarify SpecRes, Choice for image annos

- source/api/search/0.9/index.md
I was going to say over on #820 that I'm :ok: with the 'copy and not redirect' approach, but that we should at least keep 0.9 out of the sitemap. This does that.
> keep search 0.9 out of sitemap

- config/deploy.rb
For #700. This should ping google after the build has completed. Not sure how to test the Capistrano workflow without being able to deploy. The http call has been tested and Google does pick it up. Namespacing under notify allows future notifications to be slotted in if there are other services to notify.
> Added Google notification

- config/deploy.rb
⬆️ that, despite the name of the branch,
> fix application variable so that we can deploy

- source/api/index.md
- source/api/presentation/2.1/index.md
- source/api/search/1.0/index.md
See: http://jp_typos.iiif.io/api/
> Link jp translations, fix minor typos

- source/api/auth/0.9/index.md
Looking at the __Terminology__ sections of the other specs, we've never defined terms before, so this is uncharted territory, but I think this makes sense, especially since we bold __access cookie__ and __access token__ in 1.2/1.3.
Related: should we define those __access cookie__ and __access token__ in 1.1? I think it makes sense to do so in context (as we do now), but it's not terribly consistent. For now I've added a sentence to the end of 1.1, but it's in a separate commit that I can step back if we disagree.
> Bold introduction of Content and Description Resources

- source/community/index.html
See http://link_to_events.iiif.io/community/ so people can actually get to the Events page
> added link to events on community page

- source/css/spec-doc.scss
- source/css/spec-doc2.scss
Fixes #606. Have checked on current Chrome/Firefox/Safari on Mac.
> Fix lineheight for RFC highlighted text

- source/api/auth/0.9/index.md
- source/css/spec-doc2.scss
Fix for #894: Additive change to CSS to avoid breaking other things. Use is:
```
| Table | In | Here |
| ----- | -- | ----- |
| Who | Knows | What? | 
{: .api-table .first-col-normal }
```
and `Who` will not be monospaced. Applied to Auth spec for [patterns table](http://iiif.io/api/auth/0.9/#service-description) and [change log](http://iiif.io/api/auth/0.9/#d-change-log)
> Add class first-col-normal for tables where we don't want monospace

- source/event/2016/thehague.md
- source/event/index.md
Linked sched to The Hague event page, also added "Week of June 5" to The Vatican listing.
See http://hague_schedule.iiif.io/event/
And: http://hague_schedule.iiif.io/event/2016/thehague/
> linking sched to hague event page

- source/api/auth/0.9/implementation.md
- source/api/auth/0.9/index.md
- source/api/auth/0/context.json
for #528, #923, #924 
I have also added terms to the context for header, confirmLabel etc - but can any of them reuse vocab from elsewhere?
> update implementation notes to match spec

- source/event/2016/thehague.md
Added full schedule including lightning talks to the Event page for The Hague, see http://hague_sched_full.iiif.io/event/2016/thehague/#schedule
> added full schedule with timetables

- source/api/auth/0.9/implementation.md
- source/api/auth/0.9/index.md
I've taken a pass over the [auth implementation notes](http://iiif.io/api/auth/0.9/implementation/) and made a number of minor editorial changes. I think they are very nearly there. I have
* Used either "IIIF Authentication Specification" or "specification", avoided intermediate "Authentication Specification".
* Change to use US spelling: authorised -> authorized, behaviour -> behavior, customise -> customize, optimize -> optimize, summarise -> summarize
* I have removed all use of "you" in the description, replacing with some variant of "the client" (IE section)
* Fixed section numbering
Questions:
* Should we link "XMLHttpRequest API" to https://xhr.spec.whatwg.org/ ?
* I still find it awkward that we switch between countable and uncountable use of "script" -- anyone else?
* Should …
> Editorial work to refine auth implementation notes

- source/css/spec-doc2.scss
It seems that the line spacing for the `<strong>` in `.warning` blocks was fixed sometime earlier but has been broken (leading to large space to following line) for `.alert` and `.note` blocks. Change fixes that and adds a little extra space between the end of the `<strong>` block and following text because we don't seem to put any punctuation in there.
> Fix line spacing for alert and note blocks, add space after strong

- source/event/2016/thehague.md
added "Time Machine FET Flagship" by Frederic Kaplan lightning talk to the end of the lightning round for The Hague: http://add_lightning_talk.iiif.io/event/2016/thehague/
> added EPFL lightning talk

- source/event/index.md
moved The Hague to previous events: http://update_events.iiif.io/event/
> moved The Hague to past events

- source/api/annex/notes/jsonld.md
Found "Presentation API" in http://iiif.io/api/annex/notes/jsonld/#frames linked to 2.0, changed this and example code to use Jekyll site vars to get current versions.
> Use site vars for API version links

- source/api/image/2/info_frame.json
The current Image API [JSON-LD frame](http://iiif.io/api/image/2/info_frame.json) specifies:
``` json
"protocol": "http://iiif.io/api/image/"
```
whereas the [Image API spec](http://iiif.io/api/image/2.1/#technical-properties) defines it as `http://iiif.io/api/image` (no trailing slash). Since the spec is normative and the frame is not (and obviously nobody using in anger since this error results in `protocol` missing from framed output), the solution is simply to update the frame.
> Fix protocol URI in image frame

- source/community/groups/av/index.md
In an effort to provide consistent information across all IIIF groups (the A/V group was first to comply) - working with Jason, I added additional info to the group page to make it easier to learn more and get involved with the group - see changes http://av_group_page_update.iiif.io/community/groups/av/ 
Closes #950
> Av group page update

- source/api/presentation/2.1/index.md
It's not "a future IIIF Specification" any more
> Search API link from Presentation

- source/_data/institutions.yml
See http://add_europeana_kyoto.iiif.io/community/consortium/#members
closes #988 and closes #989 
This list is finally up to date - we have 39 IIIF-C members (Yale is listed as two entities but they are technically one member)
> added Europeana and Kyoto University to IIIF-C list

- source/community/groups/software/index.md
added standardized "organization" fields to the software devs group page: http://devs_group_update.iiif.io/community/groups/software/ 
Closes #974
> added standard info to software devs group page

- source/community/index.html
As noted in https://github.com/IIIF/iiif.io/pull/965 as well as indicated in verbal feedback from multiple individuals, the long list of community institutions was previously hindering access to information about how to engage with the IIIF community. I'm hoping this iteration makes the information more accessible and more clear for the time being, note specifically:
- Intro sentences describing the community
- Bringing code of conduct up into intro
- How to get involved front and center
- Action words for each type of engagement
- calendar and google drive linked
- participating institutions list at the bottom
I'm open to feedback. Thanks!
> general improvements to community page

- source/_includes/head.html
- source/_posts/2016-11-15-newsletter.md
- source/css/main.scss
I put the first IIIF Community Newsletter in the News section so as to provide a publishing platform to point people to...I was able to check my changes, links, etc. locally, but now I'm a bit confused as to why the post isn't showing up for me here: http://news_newsletter.iiif.io/news/  - file saved in iiif.io/source/_posts/2016-11-15-newsletter.md
Aiming to send newsletter out via email and point people to news posting on Nov. 15...Thanks!
> added first newsletter to news

- source/community/groups/av/index.md
- source/community/groups/museums/index.md
- source/community/groups/software/index.md
In updating the manuscripts and newspapers group pages I realized it's better to include 1 US number and then link to the international numbers like we do with community calls - so I went ahead and updated Av: http://international_call_info.iiif.io/community/groups/av/ , Museums: http://international_call_info.iiif.io/community/groups/museums/ , and Software devs: http://international_call_info.iiif.io/community/groups/software/
Once newspapers and manuscripts are merged, they will all have the same language in the call connection field.
> added link to international numbers for av, museums, and devs groups

- source/community/groups/newspapers/index.md
Made a few edits to the newspapers group page as part of the group page standardization effort - moved a few links up into the About section, added meeting schedule and call info to the Organization section - see http://newspapers_group.iiif.io/community/groups/newspapers/
Standby for +1 from kestlund and glen.robson...
> standardized newspapers group page and added meeting info

- scripts/call_calendar_generator.rb
per community call guidelines, added additional CoCo members and group leaders to call moderator rotation script, with exception of those who opted out.
scripts/call_calendar_generator.rb
> added names to call moderator rotation

- source/community/groups/museums/index.md
New bluejeans link for administrative purposes: http://museums_meeting_link.iiif.io/community/groups/museums/
> new bluejeans link for museums group

- source/_data/institutions.yml
University of Basel Digital Humanities Lab is joining the IIIF Consortium - added them to the list: http://univ_basel.iiif.io/community/consortium/#members
Closes #1022
> added univ of basel to consortium list

- source/community/call/index.md
- source/community/index.html
To make it easier for people to join the community calls, I put all of the call info in one place (similar to the group call info). See: http://community_call_page.iiif.io/community/call/
closes #1032
> added better info for community calls

- source/event/2017/vatican-cfp.md
- source/event/2017/vatican.md
Added CfP info to website: http://vatican_cfp.iiif.io/event/2017/vatican-cfp/, linked from http://vatican_cfp.iiif.io/event/2017/vatican/
> publishing vatican call for proposals

- source/community/groups/av/index.md
We now have a new bluejeans link with the correct moderator passcode, and I added Tom as chair: http://update_av_group.iiif.io/community/groups/av/ 
More updates - link to charter, and link to Tom's gist, and potential co-chair - can be added later
> new bluejeans link for av and updated chair info

- source/_posts/2017-01-30-univ-basel-joins-iiifc.md
News announcement for new consortium member: http://basel_news.iiif.io/news/2017/01/30/univ-basel-joins-iiifc/ closes #1023
> university of basel joins consortium announcement

- source/event/2017/vatican-cfp.md
- source/event/2017/vatican-sponsors.md
- source/event/2017/vatican.md
Added info about Sponsorship: http://vatican_sponsors.iiif.io/event/2017/vatican-sponsors/
Updated from"2nd annual..." to "2017 IIIF Conference" on other event pages: http://vatican_sponsors.iiif.io/event/2017/vatican/ and http://vatican_sponsors.iiif.io/event/2017/vatican-cfp/
Added clarification on 2 separate events, and Call for Sponsors link on main event page: http://vatican_sponsors.iiif.io/event/2017/vatican/
> added sponsorship info and a few updates

- source/event/2017/edinburgh.md
Event dates were switched - they are correct now: http://scotland_dates.iiif.io/event/2017/edinburgh/
> dates were switched, fixed them

- source/event/2017/vatican.md
- source/index.html
Mirador and UV meetings will be Monday June 5 prior to Showcase and Conference. I added this information to the event page: http://monday_vatican.iiif.io/event/2017/vatican/
I also updated homepage news item to highlight conference registration: http://monday_vatican.iiif.io/
> added Monday Mirador and UV meetings

- source/api/auth/0.9/index.md
- source/api/auth/1.0/index.md
- source/api/search/0.9/index.md
- source/api/search/1.0/index.md
FIrst drafts of search and auth APIs were published in 2015 and so that should be start of year range in copyright statement. (Looks silly to say 2012-2017 to me, and misleading)
> Correct copyright start date to 2015

- source/community/groups/framework.md
Updated Group Framework page to clarify TSG discussions and TSG process for choosing group chairs, scheduling meetings, per: https://docs.google.com/document/d/1E1u82AiEbEfSqyrRvdMMywcbJSrWifZY7SPzaM5zigg/edit#
See: http://group_doc_update.iiif.io/community/groups/framework/#technical-specification-group-formation-and-approval
> added clarification in tsg formation and approval section

- source/community/groups/av/index.md
- source/community/groups/discovery/index.md
- source/community/groups/manuscripts/index.md
- source/community/groups/museums/index.md
- source/community/groups/newspapers/index.md
- source/community/groups/software/index.md
Added additional chairs to Discovery (Matt) and Manuscripts (Rachel and Jeff). Standardized Organization "sub-bullet" layout across groups.
AV: http://groups_updates.iiif.io/community/groups/av/
Discovery: http://groups_updates.iiif.io/community/groups/discovery/
Manuscripts: http://groups_updates.iiif.io/community/groups/manuscripts/
Museums: http://groups_updates.iiif.io/community/groups/museums/
Newspapers: http://groups_updates.iiif.io/community/groups/newspapers/
Software Devs: http://groups_updates.iiif.io/community/groups/software/
> minor updates to group pages

- source/event/2017/vatican-sponsors.md
dates for parallel sessions were incorrect - now they are fixed. 
See http://sponsorship_dates.iiif.io/event/2017/vatican-sponsors/
> corrected parallel session dates

- source/event/2017/vatican.md
- source/event/index.md
Added links to Sched - first iteration includes primarily parallel sessions. Tuesday schedule and Wed. Lightning Talks + Demo session details to be added asap. Also will be adding sponsors info asap.
http://vatican_schedule.iiif.io/event/2017/vatican/
Also moved Edinburgh event down: http://vatican_schedule.iiif.io/event/
> link to sched, other updates

- source/event/2017/vatican.md
added first three sponsors to the event page - sponsorship benefits begin once payment has been received.
See: http://adding_sponsors.iiif.io/event/2017/vatican/
> added sponsors so far to vatican event page

- source/api/presentation/2.1/index.md
Fixes #941. Makes the rectangular section clearly different by moving to end, adds rotated case as suggested.
> move non-rect section, add rotated

- source/api/presentation/2/context.json
As it prevents correct compaction, per #946.
> DONOTMERGE, WIP: Fix context, frames

- source/community/faq/index.md
- source/community/groups/museums/index.md
http://museums_faq.iiif.io/community/groups/museums/
- added "About" and "Purpose" sections per other community group pages
- About section includes list of museums working with IIIF, and benefits/implications for museums generated by museums group
- links to general FAQ
http://museums_faq.iiif.io/community/faq/
- added some Qs that were generated in museums group, but apply to more than just museums
Notes: this is first iteration. template examples/info about IIIF at specific museums will likely take a bit longer to finalize and get online. Additional general FAQs will be added later, need to launch community effort to flesh out.
@mikeapp @azaroth42 feedback welcome.
> added content from museums group faqs

- source/_posts/2017-05-01-letter-to-dams.md
last minute addition to DAMS letter: http://aic_damsletter.iiif.io/news/2017/05/01/letter-to-dams/ @azaroth42 @mikeapp
> added Art Institute of Chicago to DAMS letter

- source/_posts/2017-04-12-vatican-conference.md
- source/event/2017/vatican.md
new sponsor - see http://sponsor_4science.iiif.io/news/2017/04/12/vatican-conference/ and http://sponsor_4science.iiif.io/event/2017/vatican/
> added sponsor 4science to vatican info

- source/api/presentation/2.1/change-log-211.md
- source/api/presentation/2.1/index.md
NOTE WELL: This change is very late breaking, but completely trivial.
> fix profile URIs

- source/community/call/index.md
@zimeon there was a slight issues with the comm call url. should be fixed now at http://comm_call.iiif.io/community/call/
> deleted spaces in zoom url

- source/event/2017/toronto.md
http://toronto-sessions.iiif.io/event/2017/toronto/
Parallel sessions only for now; still finalizing some plenary details. There is an admin issue with Sched that needs to be resolved before Sched can go live, so I will add link to Sched, and plenary details, later.
@azaroth42
> adding session schedule for toronto working meeting

- source/_data/institutions.yml
- source/_posts/2017-08-30-newsletter.md
I had the wrong link for SLU. It's correct now.
http://slu-linkfix.iiif.io/community/
http://slu-linkfix.iiif.io/news/2017/08/30/newsletter/
> fixed link for SLU Ong center

- source/api/image/validator/download.html
From @cbeer comment on Slack, the license isn't clear.
> Make image validator test images explicitly CC0

- .travis.yml
Travis changes to make a branch that has a sub domain of IIIF link to the root rather than the branch name. Once this is merged it should make the css and links work for:
http://prezi3.iiif.io/api/presentation/3.0/
Once this is merged Ill look at putting a forward for:
http://preview.iiif.io/api/prezi3/api/presentation/3.0/
so it forwards to the above as once this is merged the css and links won't work for preview.
> Make http://prezi3.iiif.io/ work

- source/api/presentation/3.0/index.md
Closes #1155 ; disallow interstitial resources such as splash pages, and recommend Auth for gating access.
> no interstitial, recommend auth

- source/api/presentation/3.0/index.md
> Language & choicehint

- source/api/presentation/3.0/index.md
Closes #920 ; explicitly disallow the `@graph` pattern from JSON-LD compaction.
> disallow @graph

- source/api/image/1/context.json
- source/api/image/2/context.json
- source/api/presentation/2/context.json
- source/api/search/0/context.json
- source/api/search/1/context.json
Closes #1272 ; removes data types and class assertions from contexts, which prevent compaction (and don't do what we thought they did anyway)
> remove datatype assertions from contexts

- source/api/presentation/3.0/index.md
Closes #880 ; adds rules about fragments to description of `id`
> Add use of fragment URIs to id

- source/api/annex/notes/design_patterns.md
Closes #1267 ; Closes #1144 ; clarifies that the round trip is for a single document, and mushing everything into a triplestore might result in documents changing shape.
> Clarify single document for LOD round trip

- source/api/presentation/3.0/index.md
Closes #1073 ; rename viewingHint/renderingHint to behavior, and viewingDirection/renderingDirection back to viewingDirection.
> behavior and viewingDirection

- source/api/index.md
Add prezi3 link to the draft specs.
Remove request for implementation and feedback for Auth draft.
Clarify that we don't guarantee availability of non current major versions of resources (re v1.0 contexts)
> Add prezi3 to /api in draft list

- source/api/presentation/3.0/index.md
Closes #1242 ; replaces description with summary throughout.
> description -> summary (#1242)

- .travis.yml
- README.md
Made a change so you specifically have to edit the .travis.yml to say its a root branch (i.e. it has a domain like prezi3.iiif.io). This means if you create a branch from prezi3 the preview link will work.
> Simplify root apps

- source/api/presentation/3.0/index.md
Closes #1334 
Changes `http://example.org` to `https:/example.org` everywhere in new spec/annex, also removes a few `www.` prefixes
> Use https for example.org URIs

- source/_includes/links.md
- source/api/presentation/3.0/index.md
This will, I think, close out all of the cross version issues.
> service uses target doc version, collections collect current doc version

- source/api/image/3.0/index.md
> make sure 1+ are always []

- source/api/annex/openannotation/index.md
- source/api/presentation/3.0/index.md
Closes #953, #1332, #1338, #1386, #1387.
> 1332 selectors

- .gitignore
- .travis.yml
- Gruntfile.js
- package.json
- source/api/image/validator/index.html
- source/api/image/validator/results.html
- source/api/presentation/validator/service/index.html
Port of @glenrobson's changes in #1514 but without the API spec changes:
This is now building OK. So after some extensive investigation it looks like grunt-html was updated to 9.0.0 but not sure why as it should have been pinned to 3.0.0 or a semantically similar version. 
Anyway version 9 wasn't working due to the node version we were using was too old to support it. On the image-rights branch I've got it working by changing:
* the travis build server we are using to trusty
* increasing the versions for ruby and grunt-html 
* removing the JAVA_OPTIONS which was causing grunt-html to fail in the travis file
* Fixing some validation errors that the new grunt-html picked up (no longer necessary to have the type attribution in ```<script type="text/javascript">```)
* Added an ignore when …
> grunt fixes

- source/_data/navigation.yml
This change is to make the API website consistent with the iiif.io website with Events at the top level. Currently they are buried in the community section and see very little use. 
The events page now contains a list of IIIF events people are attending and so should change more frequently. 
This pull request needs to be done close to https://github.com/IIIF/website/pull/71.
> Moving events to the top level

- source/api/presentation/3.0/index.md
For #1572, #1568
An arrangement to consider.
- rearrangement of intro
- removed link to (currently outdated) use case document http://iiif.io/api/presentation/usecases/ (should we update this?)
- changed language warning about discovery use cases, as this was I think misinterpreted - "the selection of interesting objects" was a motivation for the Curation API
> rearrange introduction

- source/_includes/links.md
- source/api/image/3.0/change-log.md
Trivial fix to fix link that currently goes to wrong deprecation warning
> Fix link to sizes deprecation warning in Image 3.0 change log

- source/api/image/3.0/index.md
Examples of `requiredStatement` in image 3.0 draft are wrong. Values of `label` and `value` _MUST_ have an array for every language key per http://iiif.io/api/presentation/3.0/#43-language-of-property-values
> Add arrays around strings in language maps

- Rakefile
- _config.yml
- scripts/check_mixedcontent.sh
- source/_includes/head.html
- source/_includes/spec-head.html
- source/api/image/1.1/change-log.html
- source/api/image/1.1/compliance.html
- source/api/image/validator/js/select.js
- source/api/metadata/1.0/index.html
- source/model/shared-canvas/1.0/index.html
Adding test to check for mixed content
Pointing fonts to use https versions.
Plan is to run the iiif.io site in parallel as both http and https while we look at what needs to change in the site. Things that might need to change are:
* Fixtures (moving from http://iiif.io to https://iiif.io
* Specs? do we need to change the link to the context to use the https link?
I've checked the validators and they should work OK as they don't have any client side code to retrieve http manifests.
> Updating links to work with https

- source/api/presentation/3.0/index.md
> id everywhere plus deref explanation

- source/api/image/3.0/index.md
- source/api/presentation/3.0/index.md
Reverts #1656, this should have been against `image-prezi-rc2` instead of `master`
> Revert "Recommend support for HEAD in Image and Presentation 3.0"

- source/api/image/3.0/change-log.md
Reverts IIIF/api#1657, this should have been against `image-prezi-rc2` instead of `master`
> Revert "Add note about change to canonical form of tile requests"

- Gemfile.lock
There is a warning for ffi 1.9.23 which is addressed by updating to 1.9.24. I'm not sure why this was pinned but from a look at various of the API docs I don't see anything broken.
I think this should be merged into `master` and then we can later update `image-prezi-rc2`
> Update ffi version

- source/api/auth/1.0/implementation.md
Includes typo fixes from #1684 and some UK->US spelling changes. This is a dated document so added "Fix typos" entry in document log.
> Fix typos and use American spelling in Auth implementation notes

- source/_includes/links.md
- source/api/presentation/3.0/index.md
Closes #1639 
Closes #1698 
Preview: https://preview.iiif.io/api/1639-provider/api/presentation/3.0/#provider
> Add provider, change logo to 1:1

- source/api/discovery/0.1/index.md
The redirect for `/api/discovery/` was left in 0.1 as well as being present in 0.2. The PR removes from 0.1 so that the redirect is to 0.2. Fixes #1770
> Remove leftover redirect from discovery/0.1

- source/api/image/3.0/index.md
ARK, like URN, should be capitalized, I believe.
> Capitalize ARK acronym

- source/api/presentation/3/combined-context.json
The members of [`sizes`](https://iiif.io/api/image/3.0/#53-sizes) in the image information response have an optional `type` which must always be `Size`. `Size` is not defined in the `combined-context.json`, neither [online](https://iiif.io/api/presentation/3/combined-context.json) nor in the master or the image-prezi-rc2 branch. But I guess it should ultimately expand to `http://iiif.io/api/image/3#Size`.
Same issue with `Tile` / `http://iiif.io/api/image/3#Tile` as type for each object in `tiles`.
I don't know if I selected the right branch to base this PR on...
> Add term definitions for 'Size' and 'Tile' to combined-context.json

- source/_includes/links.md
- source/api/discovery/0.3/index.md
Add:
* `partOf` to OrderedCollection (which will be scoped in, to avoid collisions) to refer to an aggregating OrderedCollection
* Rename `context` back to `seeAlso` given that we have our own context again
* Add section 3.4, describing `@context` and use of extensions, following Prezi3 pattern.
* Add section 4, on protocol related matters, notably:
* Negotiable resources
* Authentication / network issues
Updated:
* links, version number
> discovery 0.3 update

- source/api/annex/notes/disclaimer.md
Fixes #1734 
Looking at the documents we have I think everything we want this to apply to is in JSON so I went ahead and used that is clearer and more specific than some general comment about "machine readable".
> Note that JSON docs are CC0

- source/api/image/2/level2.json
Closes #1766 (as it's not semantically versioned, we can do this at any time)
> remove profileLinkHeader from v2/l2

- source/api/presentation/3.0/change-log.md
Does not address the two open issues, but otherwise I think covers all image-prezi-rc2 presentation issues.
Does not include (from previous changelogs as precedent) changes to context documents, and doesn't explicitly list all typo / minor editorial tweaks.
Does not link TRC issues. Open question as to whether it should.
> Update prezi changelog

- source/api/image/3.0/compliance.md
- source/api/image/3.0/index.md
> Image info response must include all qualities beyond default

- source/api/image/3.0/index.md
Provides description of upscaling error codes (not implemented vs bad request) and uses example of `^pct:120` as a case where the server might return 501.   
Also note canonical form is `pct:n` for `n` <=100
Closes #1741 and #1824
> ^pct:n clarification and canonical values for upscaling

- source/api/image/3.0/compliance.md
> Mark w,h syntax required at level1

- .gitignore
- source/api/presentation/validator/service/index.html
Changes to the validator html code to add 3.0 as an option. Includes changes to the javascript as the return from the 3.0 jsonschema is different to the 2.x responses.
> Presentation validator 3.0

- source/_includes/links.md
- source/api/image/3.0/index.md
- source/api/presentation/3.0/index.md
Closes #1891 
This is against `master` because we want to update the live beta docs. If merged it might also be good to merge that back into the `image_presi_rc3` branch to avoid any possible later conflicts.
> Tone down beta warning

- source/api/presentation/3.0/change-log.md
Closes #1859 by adding an item explaining removal of `otherContent`
Also fix lists of issue numbers to use 'and' consistently before the last one.
> Explain removal of 'otherContents'

- source/api/content-state/0.2/index.md
> Use en-us spelling in content-state

- source/api/image/3.0/change-log.md
This also needs https://github.com/IIIF/api/pull/1906 to be merged, although they shouldn't conflict.
> Bring image changelog up to date

- source/api/presentation/3.0/index.md
Link all occurrences of embedded/referenced in presentation api to the terminology section.
Move the explicit callout from language to id for referenced.
> link embedded/referenced terminology

- source/api/index.md
To avoid confusion and also to use the full name, I would rename Search API to Content Search API on the API Specifications page.
> Search API --> Content Search API

- source/api/index.md
Mouseover of the `3.0.0` links for Image and Presentation shows a "BETA" label.
Closes #1981
> Remove BETA label from 3.0 links

- source/api/auth/1.0/index.md
This PR adds a warning to the auth 1.0 spec re: the issues with third-party cookies. Let me know if any issues with the wording, placement, etc. 
Resolves issue #1979 
Here's the text:
Warning: Recent developments in the browser community to discontinue support for third-party cookies have meant that IIIF Authentication API 1.0 workflows that rely on third-party cookies are now, or will soon be, obsolete in most browsers. The [IIIF Authentication TSG](https://iiif.io/community/groups/auth-tsg/) is currently working on the next iteration of the Auth specification, which should address the third-party cookies issue. Workflows relying on first-party cookies remain unaffected by these developments. For a more detailed discussion of the issues, see [What happens if there are no third-party …
> Add warning to Auth API 1.0 re: browsers and third-party cookies

- source/api/discovery/0.9/index.md
This fixes discovery#86 and discovery#89. As normative changes, they need a new version.
Discovery TSG thinks this is the final version (with possible exception of some editorial clarity) before 1.0
> Add content-type, Refresh type to list, bump version and date

- source/api/search/2.0/index.md
- source/api/search/2/context.json
This PR instantiates version 2.0-alpha of the Content Search API and brings in a first-pass update of the syntax to be in line with the WebAnnotation model adopted by Prezi3.
Most of the changes are simple refactors of property names (e.g `@id` -> `id`, `resources` -> `items`, etc) and updates to the textual content to reference these, but there is also a general rework of the Paging section to include the deprecation of `Layer` objects and the custom paging introduced in Prez2.1, and restructure the mechanics of result paging in line with WebAnnotation.
This PR does not include any work to update the Autocomplete service section.
> Preliminary update of Content Search specification

- source/api/content-state/0.1/index.md
- source/api/content-state/0.2/index.md
- source/api/content-state/0.3/index.md
- source/api/discovery/0.9/index.md
Should fix:
/api/discovery/ -> /api/discovery/1.0/
and
/api/content-state/ -> /api/content-state/0.9/
> Fixing latest redirects

- source/_includes/links.md
- source/api/content-state/0.9/index.md
Editorial changes for #2045 from Rob.
Notably: lots of minor typos, clarifications. Restructure to format, encoding, protocol, processing.
> 2045 content state editorial

- source/_includes/links.md
- source/annex/index.md
- source/annex/notes/design_principles.md
- source/annex/notes/index.html
Design patterns are "a general, reusable solution to a commonly occurring problem within a given context in software design." according to https://en.wikipedia.org/wiki/Software_design_pattern and @mprove. 
These are principles for those patterns, not the patterns themselves. This PR renames the page and s/pattern/principle/ in the document.
> rename pattern -> principle per @mprove

- source/auth/2.0/index.md
This is a run through the Auth spec after initial JSON-LD 1.1 / Presentation 3 harmonisation.
Some of the changes here may be made obsolete by subsequent development of the spec for the 2.0 version, but addressing some minor editorial issues gives a cleaner starting point.
> Auth2 editorial "low hanging fruit"

- source/search/2.0/index.md
- source/search/2/context.json
Updates/fixes as requested by the TRC and discussed in the TSG call on 2022-07-26:
- Use Search context everywhere as it extends the Prezi context
- TermList -> TermPage in context
- Total is not in scope for how we need it in Search (inside a Term) - we need to define it to match WebAnno, which is ActivityStreams totalItems with non-negative type
- 4.2.3 - label is not a proper language map
- 4.2.2 - “track which page” -> “track which Annotation Page”
- 4.2.4 & 5.3 - fix user in examples to be a URI
> Search-v3-trcfeedback

- source/search/2.0/change-log.md
Conversion of the draft changelog document (https://docs.google.com/document/d/1kPnxa36l8pDC2GM6syuy_tNPXsWYJfDWxuwgH0akGls/edit) to markdown, with a couple of small corrections (adding missing inline code wrappers, correcting ticket numbers).
> First pass Content Search 2.0 changelog

- source/_data/apis.yml
- source/search/1.0/index.md
- source/search/2.0/index.md
* Bump the datafile version to 2.0
* Remove the alpha tag
* Update /search redirect to point to v2.0 page
Remaining question:
The previous version had a redirect from `/search/1/index.html` (and Prezi3 has `/presentation/3/index.html`) but here we have `/api/search/2/index.html`. Should that actually be `/search/2/index.html` (as presumably the /api/ part is a given due to the repo the markdown files are coming from and the github workflow here: https://github.com/IIIF/api/blob/main/.github/workflows/live.yml#L19)
> Update Content Search API versions

- source/index.md
Now Search 2.0 is live we need Search 1.0 in the https://iiif.io/api/index.html#older-versions table
> Add link to Search 1.0

- source/presentation/3.0/index.md
The currently live version of the Presentation API 3.0 has a duplicate excerpt at the end of the [timeMode](https://iiif.io/api/presentation/3.0/#timemode) description. This PR removes the erroneous second copy. It makes no change to the content of the specification.
> Remove duplicate timeMode excerpt

- source/annex/notes/design_principles.md
- source/image/2.0/change-log.md
- source/image/2.0/compliance.md
- source/image/2.1/change-log-211.md
- source/image/2.1/change-log.md
- source/image/2.1/compliance.md
- source/image/2.1/index.md
- source/image/3.0/change-log.md
- source/image/3.0/compliance.md
- source/image/3.0/implementation.md
- source/image/validator/download.html
- source/image/validator/results.html
- source/metadata/1.0/index.html
- source/presentation/2.0/change-log.md
- source/presentation/2.0/zones.md
- source/presentation/2.1/change-log-211.md
- source/presentation/2.1/change-log.md
- source/presentation/2.1/index.md
- source/presentation/2.1/zones.md
- source/presentation/3.0/change-log.md
- source/presentation/usecases.md
- source/search/2.0/change-log.md
According to the [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) you can specify redirects as:
```
redirect_from:
- /post/123456789/my-amazing-post/
```
or 
```
redirect_from: /post/123456798/
```
but not:
```
redirect_from:
/post/123456789/my-amazing-post/
```
So this fixes all of the redirects I could find. This causes problems on Windows as it tries to create directories with spaces in the filename and fails. On Mac it seems to just not create many of the redirect files.
> Fixing redirects

- source/auth/2.0/index.md
Minor changes: serial commas, "support access-control" -> "access control", "affect"->"effect", etc.
> Auth2 minor cleanup

- source/_includes/links.md
- source/auth/2.0/index.md
Updates to the spec as discussed on Auth call 28 Feb 2023
- Introduce required order in which access services _SHOULD_ be tried (`external`, `kiosk`, `active`), before we get to the flow diagram.
- Add an _algorithm_ - while this is still in review I haven't formatted the markdown into a nested list, so it only makes sense when you view the markdown source. I'll decorate this with nested lists markup (probably, rather than markdown) once we agree it looks OK.
- Fix a couple of JSON errors
- Remove some unnecessary repetitive text
> Add algorithm for auth 2 flow

- source/presentation/4.0/model.md
Questions:
* `intensity` and `volume` - restrict from use on other resources?
* Note about Spot Audio requiring a transform.  I changed to default to -y direction, like Spot Light.
> Lights, Audio, UnitValue and associated properties

- .github/workflows/preview.yml
I can disable other tests if it would be helpful but this leaves the HTML check and other checks but disables internal link checking. 
Note it doesn't stop the external link checker which doesn't stop the deploy to preview and can be ignored.
> Temporarily disabling internal link checking

- source/presentation/4.0/index.md
Reorganized current headings to give better visibility of sections (fewer ##### sections)
Added some examples and expanded the text for Containers and Annotations.
> Rationalise ### headings in P4 index

- source/presentation/4.0/model.md
> Add fileSize property on Content Resources with rationale
